version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "thirionlogan"
    reviewers:
      - "thirionlogan"
      
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule: 
      interval: "daily"
    assignees:
      - "thirionlogan"
    reviewers:
      - "thirionlogan"
