version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "live"
    target_branch: "main"
    assignees:
      - "thirionlogan"
    reviewers:
      - "thirionlogan"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
      
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "live"
    target_branch: "main"
    assignees:
      - "thirionlogan"
    reviewers:
      - "thirionlogan"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
